#!/usr/bin/env python3
"""
Read joint angles from a .npy file generated by sample_joint_from_pose.py
and publish them sequentially to the target_joint_angles topic.
"""

import rclpy
from rclpy.node import Node
from omx_cpp_interface.msg import ArmJointAngles
import numpy as np
import os
import argparse
from pathlib import Path
import time


class AnglePublisher(Node):

    def __init__(self, trace):
        super().__init__('angle_publisher')

        # Get the ROS_DOMAIN_ID aka robot number
        ros_domain_id = os.getenv("ROS_DOMAIN_ID", "0")
        try:
            if int(ros_domain_id) < 10:
                ros_domain_id = "0" + str(int(ros_domain_id))
            else:
                ros_domain_id = str(int(ros_domain_id))
        except Exception:
            ros_domain_id = "00"
        self.get_logger().info(f'ROS_DOMAIN_ID: {ros_domain_id}')

        # Arm joint angles publisher
        self.angles_pub = self.create_publisher(
            ArmJointAngles, 
            f'/tb{ros_domain_id}/target_joint_angles', 
            10
        )

        # get the trace directory path
        self.trace_dir = Path("src/DRACO/traces") / trace
        if not self.trace_dir.is_dir():
            raise FileNotFoundError(f"Trace directory not found: {self.trace_dir}")
        # then we need to get all the joints.npy files in the trace directory
        self.joints_files = list(self.trace_dir.glob("*joints.npy"))
        if not self.joints_files:
            raise FileNotFoundError(f"No joints.npy files found in trace directory: {self.trace_dir}")
        # then we need to iterate through all the joints.npy files and load the angles into a list
        # we need to let the arm move to home pose before each angle set
        # breakpoint()
        # self.angles = None
        # for joints_file in self.joints_files:
        #     # load the original data
        #     if self.angles is None:
        #         self.angles = np.load(joints_file)
        #     np.concatenate([self.angles, np.load(joints_file)])
        #     # load the home pose for ten times
        #     for i in range(10):
        #         home_pose = np.array([0, -1.494, 0.508, 1.033]).reshape(1, -1)
        #         np.concatenate([self.angles, home_pose])
        # # Handle different shapes: (4,) -> (1, 4), (N, 4) stays as is
        # if self.angles.ndim == 1:
        #     self.angles = self.angles.reshape(1, -1)
        
        # print(self.angles.shape)
        # if self.angles.shape[1] != 4:
        #     raise ValueError(f"Expected 4 joint angles per row, got shape {self.angles.shape}")
        
        # self.get_logger().info(f'Loaded {self.angles.shape[0]} sets of joint angles from {self.trace_dir}')
        
        # then we need to iterate through all the joints.npy files and build a big angle array
        # we need to let the arm move to home pose before each angle set

        home_pose = np.array([[0, -1.494, 0.508, 1.033]], dtype=np.float32)  # shape (1, 4)
        angle_blocks = []

        for joints_file in sorted(self.joints_files):
            # load the joint angles from this file
            joints = np.load(joints_file)  # .npy -> ndarray

            # Handle shapes: (4,) -> (1, 4); (N, 4) stays as-is
            joints = np.atleast_2d(joints)

            # 10 steps of home pose before this segment
            home_block = np.repeat(home_pose, 10, axis=0)

            angle_blocks.append(home_block)
            angle_blocks.append(joints)
        
        # move to home pose at the end
        home_block = np.repeat(home_pose, 10, axis=0)
        angle_blocks.append(home_block)

        # Concatenate everything into one (T, 4) array
        self.angles = np.concatenate(angle_blocks, axis=0)

        if self.angles.shape[1] != 4:
            raise ValueError(f"Expected 4 joint angles per row, got shape {self.angles.shape}")

        self.get_logger().info(
            f'Loaded {self.angles.shape[0]} sets of joint angles from {self.trace_dir}'
        )

        # Current index for publishing
        self.current_index = 0
        
        # Create timer to publish angles sequentially
        # Publish at 10 Hz (every 0.1 seconds)
        self.timer = self.create_timer(0.1, self.publish_next_angle)

    # def init_angles(self):
    #     angle_set = self.angles[self.current_index]
            
    #     arm_msg = ArmJointAngles()
    #     arm_msg.joint1 = float(0.041)
    #     arm_msg.joint2 = float(-1.494)
    #     arm_msg.joint3 = float(0.508)
    #     arm_msg.joint4 = float(1.033)
        
    #     self.angles_pub.publish(arm_msg)
    #     self.get_logger().info(
    #         f'Published init angle set : '
    #         f'[{arm_msg.joint1:.4f}, {arm_msg.joint2:.4f}, {arm_msg.joint3:.4f}, {arm_msg.joint4:.4f}]'
    #     )
        
    #     self.current_index += 1
    #     if self.current_index < self.angles.shape[0]:
    #         angle_set = self.angles[self.current_index]
            
    #         arm_msg = ArmJointAngles()
    #         arm_msg.joint1 = float(angle_set[0])
    #         arm_msg.joint2 = float(angle_set[1])
    #         arm_msg.joint3 = float(angle_set[2])
    #         arm_msg.joint4 = float(angle_set[3])
            
    #         self.angles_pub.publish(arm_msg)
    #         self.get_logger().info(
    #             f'Published angle set {self.current_index + 1}/{self.angles.shape[0]}: '
    #             f'[{arm_msg.joint1:.4f}, {arm_msg.joint2:.4f}, {arm_msg.joint3:.4f}, {arm_msg.joint4:.4f}]'
    #         )
            
    #         self.current_index += 1
    #     else:
    #         # All angles published, stop the timer
    #         self.get_logger().info('Finished publishing all joint angles')
    #         self.timer.cancel()

    def publish_next_angle(self):
        """Publish the next set of joint angles."""
        # self.get_logger().info(self.angles.shape[0])
        if self.current_index < self.angles.shape[0]:
            angle_set = self.angles[self.current_index]
            # self.get_logger().info(angle_set)
            
            arm_msg = ArmJointAngles()
            arm_msg.joint1 = float(angle_set[0])
            arm_msg.joint2 = float(angle_set[1])
            arm_msg.joint3 = float(angle_set[2])
            arm_msg.joint4 = float(angle_set[3])
            # self.get_logger().info(arm_msg)
            
            self.angles_pub.publish(arm_msg)
            self.get_logger().info(
                f'Published angle set {self.current_index + 1}/{self.angles.shape[0]}: '
                f'[{arm_msg.joint1:.4f}, {arm_msg.joint2:.4f}, {arm_msg.joint3:.4f}, {arm_msg.joint4:.4f}]'
            )
            
            self.current_index += 1
        else:
            # All angles published, stop the timer
            # for i in range(10):
            #     joints_msg = ArmJointAngles()
            #     joints_msg.joint1 = float(0)
            #     joints_msg.joint2 = float(-1.494)
            #     joints_msg.joint3 = float(0.508)
            #     joints_msg.joint4 = float(1.033)
            self.get_logger().info('Finished publishing all joint angles and reset the arm')
            self.timer.cancel()


def main(args=None):
    parser = argparse.ArgumentParser(
        description="Publish joint angles from .npy file to ROS2 topic"
    )
    parser.add_argument(
        '--trace',
        type=str,
        required=True,
        help='Path to folder containing all .npz files'
    )
    parser.add_argument(
        '--rate',
        type=float,
        default=10.0,
        help='Publishing rate in Hz (default: 10.0)'
    )
    
    # Parse known args to avoid conflicts with rclpy
    parsed_args, unknown = parser.parse_known_args()
    
    rclpy.init(args=args)
    
    try:
        angle_publisher = AnglePublisher(parsed_args.trace)
        
        # Adjust timer rate if specified
        if parsed_args.rate != 10.0:
            angle_publisher.timer.cancel()
            angle_publisher.timer = angle_publisher.create_timer(
                1.0 / parsed_args.rate, 
                angle_publisher.publish_next_angle
            )
        
        time.sleep(2)  # Wait for publisher to set up
        rclpy.spin(angle_publisher)
        
    except Exception as e:
        print(f"Error: {e}")
    finally:
        if 'angle_publisher' in locals():
            angle_publisher.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()

